[workspace]
dependencies_update = true
changelog_update = true
pr_labels = ["release"]
semver_check = true
publish_timeout = "10m"
git_tag_enable = false
git_release_enable = false
publish = false
repo_url = "https://github.com/demml/potato_head"

[[package]]
name = "baked-potato"
publish = true

[[package]]
name = "potato-agent"
publish = true

[[package]]
name = "potato-head"
publish = true

[[package]]
name = "potatohead-macro"
publish = true

[[package]]
name = "potato-provider"
publish = true

[[package]]
name = "potato-state"
publish = true

[[package]]
name = "potato-type"
publish = true

[[package]]
name = "potato-util"
publish = true

[[package]]
name = "potato-workflow"
publish = true
