[package]
name = "potatohead-macro"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

license = "MIT"
description = "Macros for Potato"


[lib]
proc-macro = false  


[dependencies]
thiserror = { workspace = true }